# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Entrypoint

on:
  push:
    paths:
    - 'CMakeLists.txt'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cxx'
    - '**/*.c'
    - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
  
env:
  BUILD_TYPE: Release
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_PATCH: 0

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/honigkuchen/${{ github.event.repository.name }}
      options: --user root
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake --preset GithubMakefileConfigurationPreset \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DPROJECT_VERSION_MAJOR:INT=${{env.VERSION_MAJOR}} \
            -DPROJECT_VERSION_MINOR:INT=${{env.VERSION_MINOR}} \
            -DPROJECT_VERSION_PATCH:INT=${{env.VERSION_PATCH}}
          cmake --build --preset GithubMakefileBuildPreset

      - name: Pack debian
        run: |
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake

      - name: Upload debian
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} debian package
          path: ${{github.workspace}}/*.deb