# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build C++

on:
  push:
    branches:
      - main
    paths:
    - 'CMakeLists.txt'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cxx'
    - '**/*.c'
    - '.github/workflows/c-cpp.yml'
  pull_request:
    branches:
      - main
  
env:
  BUILD_TYPE: Release
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_PATCH: 0

jobs:
  build_cpp17:
    # github.com/the-coding-library/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    with:
      build_type: "Release"
      cpp_standard: 17
      version_major: 1
      version_minor: 0
      version_patch: 0
      
  build_cpp20:
    # github.com/the-coding-library/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    with:
      build_type: "Release"
      cpp_standard: 20
      version_major: 1
      version_minor: 0
      version_patch: 0

  build_cpp23:
    # github.com/the-coding-library/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    with:
      build_type: "Release"
      cpp_standard: 23
      version_major: 1
      version_minor: 0
      version_patch: 0