# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build devcontainer

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build devcontainer
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/honigkuchen/${{ github.event.repository.name }}
        cacheFrom: ghcr.io/honigkuchen/${{ github.event.repository.name }}
        push: always