# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Entrypoint

on:
  push:
    branches:
      - main
    paths:
    - 'CMakeLists.txt'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cxx'
    - '**/*.c'
    - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
  
env:
  BUILD_TYPE: Release
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_PATCH: 0

jobs:
  build_expect_successful:
    strategy:
      matrix:
        cpp_standard: [17, 20, 23]
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      build_type: "Release"
      cpp_standard: ${{ matrix.cpp_standard }}
      version_major: 1
      version_minor: 0
      version_patch: 0

  build_expect_fail:
    strategy:
      matrix:
        cpp_standard: [11]
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      build_type: "Release"
      cpp_standard: ${{ matrix.cpp_standard }}
      version_major: 1
      version_minor: 0
      version_patch: 0
      expect_fail: true

  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/honigkuchen/${{ github.event.repository.name }}
      options: --user root
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DPROJECT_VERSION_MAJOR:INT=${{env.VERSION_MAJOR}} \
            -DPROJECT_VERSION_MINOR:INT=${{env.VERSION_MINOR}} \
            -DPROJECT_VERSION_PATCH:INT=${{env.VERSION_PATCH}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Pack debian
        run: |
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake

      - name: Upload debian
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} debian package
          path: ${{github.workspace}}/*.deb